name: testlery cms CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          GITHUB_WORKSPACE: "/var/www/cms"

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: composer install
      

      
