name: testlery cms CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make symlink
        run: ln -s /var/www/cms/src/testlery-demo-cms/testlery-demo-cms /var/www/cms/current

      - name: Install dependencies
        run: cd /var/www/cms/src/current && composer install
      

      
